<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>TaskMonitoring.EmployeeDesktop</AssemblyName>
    <RootNamespace>TaskMonitoring.EmployeeDesktop</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TaskMonitoring.Employee.Shared/TaskMonitoring.Employee.Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="desktopsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
