import { useEffect, useState, type FormEvent } from 'react';
import { apiFetch } from './api';
import { useAuth } from './auth';
import type { PagedResponse } from './types';
import './management.css';

interface EmployeeOption { id: string; employeeCode: string; fullName: string; }
interface ProjectOption { id: string; code: string; name: string; status: string; }

interface Shift {
  id: string; code: string; name: string; startTime: string; endTime: string; timeZoneId: string; graceMinutes: number; isActive: boolean; assignmentCount: number;
}
interface ShiftAssignment {
  id: string; employeeId: string; employeeName: string; shiftId: string; shiftName: string; effectiveFrom: string; effectiveTo: string | null; createdAtUtc: string;
}
interface ShiftDraft { code: string; name: string; startTime: string; endTime: string; timeZoneId: string; graceMinutes: string; isActive: boolean; }
const emptyShift: ShiftDraft = { code: '', name: '', startTime: '09:00', endTime: '17:00', timeZoneId: 'Asia/Dhaka', graceMinutes: '10', isActive: true };

interface ProjectRecord {
  id: string; code: string; name: string; description: string | null; status: 'Planning' | 'Active' | 'OnHold' | 'Completed' | 'Archived'; startDate: string | null; dueDate: string | null; activeMemberCount: number; openTaskCount: number;
}
interface ProjectMember { id: string; employeeId: string; employeeCode: string; employeeName: string; role: 'Member' | 'Manager'; isActive: boolean; addedAtUtc: string; removedAtUtc: string | null; }
interface ProjectDraft { code: string; name: string; description: string; status: ProjectRecord['status']; startDate: string; dueDate: string; }
const emptyProject: ProjectDraft = { code: '', name: '', description: '', status: 'Planning', startDate: '', dueDate: '' };

interface TaskRecord {
  id: string; projectId: string; projectCode: string; projectName: string; title: string; description: string | null; status: 'ToDo' | 'InProgress' | 'Blocked' | 'Done' | 'Cancelled'; priority: 'Low' | 'Normal' | 'High' | 'Urgent'; assigneeEmployeeId: string | null; assigneeName: string | null; dueDate: string | null; completedAtUtc: string | null; commentCount: number;
}
interface TaskDraft { projectId: string; title: string; description: string; priority: TaskRecord['priority']; assigneeEmployeeId: string; dueDate: string; }
const emptyTask: TaskDraft = { projectId: '', title: '', description: '', priority: 'Normal', assigneeEmployeeId: '', dueDate: '' };

function timeInput(value: string): string { return value.length >= 5 ? value.slice(0, 5) : value; }
function timePayload(value: string): string { return value.length === 5 ? `${value}:00` : value; }
function Status({ value }: { value: string }) { return <span className={`status-badge status-${value.toLowerCase()}`}>{value}</span>; }

export function ShiftManagementPage() {
  const { can } = useAuth();
  const mayManage = can('shifts.manage');
  const [shifts, setShifts] = useState<Shift[]>([]);
  const [assignments, setAssignments] = useState<ShiftAssignment[]>([]);
  const [employees, setEmployees] = useState<EmployeeOption[]>([]);
  const [draft, setDraft] = useState<ShiftDraft>(emptyShift);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [showShiftForm, setShowShiftForm] = useState(false);
  const [showAssignmentForm, setShowAssignmentForm] = useState(false);
  const [assignmentEmployeeId, setAssignmentEmployeeId] = useState('');
  const [assignmentShiftId, setAssignmentShiftId] = useState('');
  const [effectiveFrom, setEffectiveFrom] = useState(new Date().toISOString().slice(0, 10));
  const [effectiveTo, setEffectiveTo] = useState('');
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [version, setVersion] = useState(0);

  useEffect(() => {
    let cancelled = false; setLoading(true); setError('');
    Promise.all([apiFetch<Shift[]>('/api/shifts'), apiFetch<ShiftAssignment[]>('/api/shifts/assignments'), apiFetch<EmployeeOption[]>('/api/admin-lookups/shifts/employees')])
      .then(([shiftData, assignmentData, employeeData]) => { if (!cancelled) { setShifts(shiftData); setAssignments(assignmentData); setEmployees(employeeData); } })
      .catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Unable to load shift administration.'); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [version]);

  function newShift() { setEditingId(null); setDraft(emptyShift); setShowShiftForm(true); setNotice(''); setError(''); }
  function editShift(item: Shift) { setEditingId(item.id); setDraft({ code: item.code, name: item.name, startTime: timeInput(item.startTime), endTime: timeInput(item.endTime), timeZoneId: item.timeZoneId, graceMinutes: String(item.graceMinutes), isActive: item.isActive }); setShowShiftForm(true); setNotice(''); setError(''); }
  async function saveShift(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!mayManage) return; setBusy(true); setError(''); setNotice('');
    try {
      await apiFetch(`/api/shifts${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', body: JSON.stringify({ code: draft.code, name: draft.name, startTime: timePayload(draft.startTime), endTime: timePayload(draft.endTime), timeZoneId: draft.timeZoneId, graceMinutes: Number(draft.graceMinutes), ...(editingId ? { isActive: draft.isActive } : {}) }) });
      setNotice(`Shift ${editingId ? 'updated' : 'created'}.`); setShowShiftForm(false); setVersion(value => value + 1);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save shift.'); } finally { setBusy(false); }
  }
  async function assignShift(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!mayManage) return; setBusy(true); setError(''); setNotice('');
    try {
      await apiFetch('/api/shifts/assignments', { method: 'POST', body: JSON.stringify({ employeeId: assignmentEmployeeId, shiftId: assignmentShiftId, effectiveFrom, effectiveTo: effectiveTo || null }) });
      setNotice('Shift assignment created.'); setShowAssignmentForm(false); setAssignmentEmployeeId(''); setAssignmentShiftId(''); setVersion(value => value + 1);
    } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to assign shift.'); } finally { setBusy(false); }
  }
  return <>
    <div className="page-header"><div><p className="eyebrow">Attendance administration</p><h1>Shifts & assignments</h1><p className="muted">Timezone-aware schedules and effective-dated employee assignments.</p></div>{mayManage && <div className="header-actions"><button className="ghost-button" onClick={() => setShowAssignmentForm(true)}>Assign shift</button><button className="primary-button" onClick={newShift}>New shift</button></div>}</div>
    {notice && <div className="success-banner">{notice}</div>}{error && <div className="error-banner">{error}</div>}
    {showShiftForm && mayManage && <article className="panel management-form-panel"><div className="panel-heading"><h2>{editingId ? 'Edit shift' : 'Create shift'}</h2><button className="ghost-button" onClick={() => setShowShiftForm(false)}>Close</button></div><form className="form-grid" onSubmit={saveShift}>
      <label><span>Code</span><input required maxLength={50} value={draft.code} onChange={event => setDraft(value => ({ ...value, code: event.target.value }))} /></label><label><span>Name</span><input required minLength={2} maxLength={150} value={draft.name} onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} /></label>
      <label><span>Start time</span><input type="time" required value={draft.startTime} onChange={event => setDraft(value => ({ ...value, startTime: event.target.value }))} /></label><label><span>End time</span><input type="time" required value={draft.endTime} onChange={event => setDraft(value => ({ ...value, endTime: event.target.value }))} /></label>
      <label><span>IANA timezone</span><input required maxLength={100} value={draft.timeZoneId} onChange={event => setDraft(value => ({ ...value, timeZoneId: event.target.value }))} /><small>Example: Asia/Dhaka</small></label><label><span>Grace minutes</span><input type="number" min={0} max={180} value={draft.graceMinutes} onChange={event => setDraft(value => ({ ...value, graceMinutes: event.target.value }))} /></label>
      {editingId && <label className="check-field"><input type="checkbox" checked={draft.isActive} onChange={event => setDraft(value => ({ ...value, isActive: event.target.checked }))} /><span>Active</span></label>}
      <div className="wide-field form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save shift'}</button><button type="button" className="ghost-button" onClick={() => setShowShiftForm(false)}>Cancel</button></div>
    </form></article>}
    {showAssignmentForm && mayManage && <article className="panel management-form-panel"><div className="panel-heading"><h2>Assign shift</h2><button className="ghost-button" onClick={() => setShowAssignmentForm(false)}>Close</button></div><form className="form-grid" onSubmit={assignShift}>
      <label><span>Employee</span><select required value={assignmentEmployeeId} onChange={event => setAssignmentEmployeeId(event.target.value)}><option value="">Select employee…</option>{employees.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.employeeCode})</option>)}</select></label>
      <label><span>Shift</span><select required value={assignmentShiftId} onChange={event => setAssignmentShiftId(event.target.value)}><option value="">Select shift…</option>{shifts.filter(item => item.isActive).map(item => <option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select></label>
      <label><span>Effective from</span><input type="date" required value={effectiveFrom} onChange={event => setEffectiveFrom(event.target.value)} /></label><label><span>Effective to</span><input type="date" value={effectiveTo} onChange={event => setEffectiveTo(event.target.value)} /></label>
      <div className="wide-field form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Assigning…' : 'Assign shift'}</button></div>
    </form></article>}
    <article className="panel table-panel"><div className="panel-heading"><div><h2>Shift definitions</h2><p>{shifts.length} shifts</p></div><button className="ghost-button" onClick={() => setVersion(value => value + 1)}>Refresh</button></div>{loading ? <div className="loading-block">Loading…</div> : <div className="table-wrap"><table><thead><tr><th>Shift</th><th>Schedule</th><th>Timezone</th><th>Grace</th><th>Assignments</th><th>Status</th>{mayManage && <th>Action</th>}</tr></thead><tbody>{shifts.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td>{timeInput(item.startTime)} → {timeInput(item.endTime)}</td><td>{item.timeZoneId}</td><td>{item.graceMinutes} min</td><td>{item.assignmentCount}</td><td><Status value={item.isActive ? 'Active' : 'Inactive'} /></td>{mayManage && <td><button className="text-button" onClick={() => editShift(item)}>Edit</button></td>}</tr>)}</tbody></table></div>}</article>
    <article className="panel table-panel"><div className="panel-heading"><div><h2>Effective assignments</h2><p>{assignments.length} assignments</p></div></div><div className="table-wrap"><table><thead><tr><th>Employee</th><th>Shift</th><th>Effective range</th></tr></thead><tbody>{assignments.map(item => <tr key={item.id}><td>{item.employeeName}</td><td>{item.shiftName}</td><td>{item.effectiveFrom} → {item.effectiveTo || 'Open ended'}</td></tr>)}</tbody></table></div></article>
  </>;
}

export function ProjectManagementPage() {
  const { can } = useAuth(); const mayManage = can('projects.manage');
  const [items, setItems] = useState<ProjectRecord[]>([]); const [employees, setEmployees] = useState<EmployeeOption[]>([]); const [members, setMembers] = useState<ProjectMember[]>([]);
  const [draft, setDraft] = useState<ProjectDraft>(emptyProject); const [editingId, setEditingId] = useState<string | null>(null); const [selectedProjectId, setSelectedProjectId] = useState<string | null>(null); const [showForm, setShowForm] = useState(false); const [showMemberForm, setShowMemberForm] = useState(false);
  const [memberEmployeeId, setMemberEmployeeId] = useState(''); const [memberRole, setMemberRole] = useState<'Member' | 'Manager'>('Member');
  const [searchDraft, setSearchDraft] = useState(''); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [version, setVersion] = useState(0);
  useEffect(() => { let cancelled = false; setLoading(true); const suffix = search ? `&search=${encodeURIComponent(search)}` : ''; Promise.all([apiFetch<PagedResponse<ProjectRecord>>(`/api/projects?page=1&pageSize=100${suffix}`), apiFetch<EmployeeOption[]>('/api/admin-lookups/projects/employees')]).then(([projects, employeeData]) => { if (!cancelled) { setItems(projects.items); setEmployees(employeeData); } }).catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Unable to load projects.'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [search, version]);
  useEffect(() => { if (!selectedProjectId) { setMembers([]); return; } let cancelled = false; apiFetch<ProjectMember[]>(`/api/projects/${selectedProjectId}/members`).then(data => { if (!cancelled) setMembers(data); }).catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Unable to load project members.'); }); return () => { cancelled = true; }; }, [selectedProjectId, version]);
  function newProject() { setEditingId(null); setDraft(emptyProject); setShowForm(true); setError(''); setNotice(''); }
  function editProject(item: ProjectRecord) { setEditingId(item.id); setSelectedProjectId(item.id); setDraft({ code: item.code, name: item.name, description: item.description || '', status: item.status, startDate: item.startDate || '', dueDate: item.dueDate || '' }); setShowForm(true); setError(''); setNotice(''); }
  async function saveProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!mayManage) return; setBusy(true); setError(''); try { const payload = { code: draft.code, name: draft.name, description: draft.description || null, status: draft.status, startDate: draft.startDate || null, dueDate: draft.dueDate || null }; const saved = await apiFetch<ProjectRecord>(`/api/projects${editingId ? `/${editingId}` : ''}`, { method: editingId ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setNotice(`Project ${editingId ? 'updated' : 'created'}.`); setShowForm(false); setEditingId(null); setSelectedProjectId(saved.id); setVersion(value => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save project.'); } finally { setBusy(false); } }
  async function addMember(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!mayManage || !selectedProjectId) return; setBusy(true); setError(''); try { await apiFetch(`/api/projects/${selectedProjectId}/members`, { method: 'PUT', body: JSON.stringify({ employeeId: memberEmployeeId, role: memberRole }) }); setNotice('Project membership saved.'); setShowMemberForm(false); setMemberEmployeeId(''); setVersion(value => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save project member.'); } finally { setBusy(false); } }
  async function removeMember(item: ProjectMember) { if (!mayManage || !selectedProjectId || !window.confirm(`Remove ${item.employeeName} from this project? Open assigned tasks must be cleared first.`)) return; setBusy(true); setError(''); try { await apiFetch(`/api/projects/${selectedProjectId}/members/${item.employeeId}`, { method: 'DELETE' }); setNotice('Project member removed.'); setVersion(value => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to remove project member.'); } finally { setBusy(false); } }
  return <>
    <div className="page-header"><div><p className="eyebrow">Delivery administration</p><h1>Projects & members</h1><p className="muted">Manage project lifecycle, dates and active membership.</p></div><div className="header-actions"><form className="inline-search" onSubmit={event => { event.preventDefault(); setSearch(searchDraft.trim()); }}><input value={searchDraft} onChange={event => setSearchDraft(event.target.value)} placeholder="Search projects" /><button className="ghost-button">Search</button></form>{mayManage && <button className="primary-button" onClick={newProject}>New project</button>}</div></div>
    {notice && <div className="success-banner">{notice}</div>}{error && <div className="error-banner">{error}</div>}
    {showForm && mayManage && <article className="panel management-form-panel"><div className="panel-heading"><h2>{editingId ? 'Edit project' : 'Create project'}</h2><button className="ghost-button" onClick={() => setShowForm(false)}>Close</button></div><form className="form-grid" onSubmit={saveProject}>
      <label><span>Code</span><input required maxLength={50} value={draft.code} onChange={event => setDraft(value => ({ ...value, code: event.target.value }))} /></label><label><span>Name</span><input required minLength={2} maxLength={200} value={draft.name} onChange={event => setDraft(value => ({ ...value, name: event.target.value }))} /></label>
      <label><span>Status</span><select value={draft.status} onChange={event => setDraft(value => ({ ...value, status: event.target.value as ProjectRecord['status'] }))}><option>Planning</option><option>Active</option><option>OnHold</option><option>Completed</option><option>Archived</option></select><small>Complete/archive is rejected while open tasks remain.</small></label>
      <label><span>Start date</span><input type="date" value={draft.startDate} onChange={event => setDraft(value => ({ ...value, startDate: event.target.value }))} /></label><label><span>Due date</span><input type="date" value={draft.dueDate} onChange={event => setDraft(value => ({ ...value, dueDate: event.target.value }))} /></label>
      <label className="wide-field"><span>Description</span><textarea maxLength={4000} value={draft.description} onChange={event => setDraft(value => ({ ...value, description: event.target.value }))} /></label><div className="wide-field form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save project'}</button></div>
    </form></article>}
    <article className="panel table-panel"><div className="panel-heading"><div><h2>Projects</h2><p>{items.length} loaded</p></div><button className="ghost-button" onClick={() => setVersion(value => value + 1)}>Refresh</button></div>{loading ? <div className="loading-block">Loading…</div> : <div className="table-wrap"><table><thead><tr><th>Project</th><th>Status</th><th>Dates</th><th>Members</th><th>Open tasks</th>{mayManage && <th>Actions</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.name}</strong><small>{item.code}</small></td><td><Status value={item.status} /></td><td>{item.startDate || '—'} → {item.dueDate || 'No due date'}</td><td>{item.activeMemberCount}</td><td>{item.openTaskCount}</td>{mayManage && <td className="action-cell"><button className="text-button" onClick={() => editProject(item)}>Edit</button><button className="text-button" onClick={() => { setSelectedProjectId(item.id); setShowMemberForm(true); }}>Members</button></td>}</tr>)}</tbody></table></div>}</article>
    {selectedProjectId && <article className="panel table-panel"><div className="panel-heading"><div><h2>Project members</h2><p>{items.find(item => item.id === selectedProjectId)?.name || 'Selected project'}</p></div>{mayManage && <button className="primary-button" onClick={() => setShowMemberForm(true)}>Add member</button>}</div>{showMemberForm && mayManage && <form className="form-grid compact-form" onSubmit={addMember}><label><span>Employee</span><select required value={memberEmployeeId} onChange={event => setMemberEmployeeId(event.target.value)}><option value="">Select employee…</option>{employees.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.employeeCode})</option>)}</select></label><label><span>Role</span><select value={memberRole} onChange={event => setMemberRole(event.target.value as 'Member' | 'Manager')}><option>Member</option><option>Manager</option></select></label><div className="form-actions"><button className="primary-button" disabled={busy}>Save member</button><button type="button" className="ghost-button" onClick={() => setShowMemberForm(false)}>Cancel</button></div></form>}<div className="table-wrap"><table><thead><tr><th>Employee</th><th>Role</th><th>Status</th>{mayManage && <th>Action</th>}</tr></thead><tbody>{members.map(item => <tr key={item.id}><td><strong>{item.employeeName}</strong><small>{item.employeeCode}</small></td><td>{item.role}</td><td><Status value={item.isActive ? 'Active' : 'Inactive'} /></td>{mayManage && <td>{item.isActive && <button className="text-button danger" onClick={() => void removeMember(item)}>Remove</button>}</td>}</tr>)}</tbody></table></div></article>}
  </>;
}

const taskTransitions: Record<TaskRecord['status'], TaskRecord['status'][]> = { ToDo: ['InProgress', 'Blocked', 'Cancelled'], InProgress: ['Blocked', 'Done', 'Cancelled'], Blocked: ['InProgress', 'Cancelled'], Done: ['InProgress'], Cancelled: ['ToDo'] };

export function TaskManagementPage() {
  const { can } = useAuth(); const mayManage = can('tasks.manage');
  const [items, setItems] = useState<TaskRecord[]>([]); const [projects, setProjects] = useState<ProjectOption[]>([]); const [members, setMembers] = useState<EmployeeOption[]>([]); const [draft, setDraft] = useState<TaskDraft>(emptyTask); const [editing, setEditing] = useState<TaskRecord | null>(null); const [showForm, setShowForm] = useState(false); const [searchDraft, setSearchDraft] = useState(''); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [version, setVersion] = useState(0);
  useEffect(() => { let cancelled = false; setLoading(true); const suffix = search ? `&search=${encodeURIComponent(search)}` : ''; Promise.all([apiFetch<PagedResponse<TaskRecord>>(`/api/tasks?page=1&pageSize=100${suffix}`), apiFetch<ProjectOption[]>('/api/admin-lookups/tasks/projects')]).then(([tasks, projectData]) => { if (!cancelled) { setItems(tasks.items); setProjects(projectData); } }).catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Unable to load tasks.'); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [search, version]);
  useEffect(() => { const projectId = draft.projectId; if (!projectId) { setMembers([]); return; } let cancelled = false; apiFetch<EmployeeOption[]>(`/api/admin-lookups/tasks/projects/${projectId}/members`).then(data => { if (!cancelled) setMembers(data); }).catch(caught => { if (!cancelled) setError(caught instanceof Error ? caught.message : 'Unable to load project members.'); }); return () => { cancelled = true; }; }, [draft.projectId]);
  function newTask() { setEditing(null); setDraft(emptyTask); setShowForm(true); setError(''); setNotice(''); }
  function editTask(item: TaskRecord) { setEditing(item); setDraft({ projectId: item.projectId, title: item.title, description: item.description || '', priority: item.priority, assigneeEmployeeId: item.assigneeEmployeeId || '', dueDate: item.dueDate || '' }); setShowForm(true); setError(''); setNotice(''); }
  async function saveTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!mayManage) return; setBusy(true); setError(''); try { const common = { title: draft.title, description: draft.description || null, priority: draft.priority, assigneeEmployeeId: draft.assigneeEmployeeId || null, dueDate: draft.dueDate || null }; await apiFetch(`/api/tasks${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PUT' : 'POST', body: JSON.stringify(editing ? common : { projectId: draft.projectId, ...common }) }); setNotice(`Task ${editing ? 'updated' : 'created'}.`); setShowForm(false); setEditing(null); setVersion(value => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to save task.'); } finally { setBusy(false); } }
  async function changeStatus(item: TaskRecord, status: TaskRecord['status']) { if (!mayManage) return; const risky = status === 'Cancelled' || status === 'Done'; if (risky && !window.confirm(`Change task status to ${status}?`)) return; setBusy(true); setError(''); try { await apiFetch(`/api/tasks/${item.id}/status`, { method: 'PUT', body: JSON.stringify({ status }) }); setNotice(`Task moved to ${status}.`); setVersion(value => value + 1); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Unable to change task status.'); } finally { setBusy(false); } }
  return <>
    <div className="page-header"><div><p className="eyebrow">Work administration</p><h1>Tasks</h1><p className="muted">Create, assign, edit and transition project tasks using backend-enforced project membership rules.</p></div><div className="header-actions"><form className="inline-search" onSubmit={event => { event.preventDefault(); setSearch(searchDraft.trim()); }}><input value={searchDraft} onChange={event => setSearchDraft(event.target.value)} placeholder="Search tasks" /><button className="ghost-button">Search</button></form>{mayManage && <button className="primary-button" onClick={newTask}>New task</button>}</div></div>
    {notice && <div className="success-banner">{notice}</div>}{error && <div className="error-banner">{error}</div>}
    {showForm && mayManage && <article className="panel management-form-panel"><div className="panel-heading"><h2>{editing ? 'Edit task' : 'Create task'}</h2><button className="ghost-button" onClick={() => setShowForm(false)}>Close</button></div><form className="form-grid" onSubmit={saveTask}>
      <label><span>Project</span><select required disabled={Boolean(editing)} value={draft.projectId} onChange={event => setDraft(value => ({ ...value, projectId: event.target.value, assigneeEmployeeId: '' }))}><option value="">Select project…</option>{projects.map(item => <option key={item.id} value={item.id}>{item.name} ({item.code})</option>)}</select></label><label><span>Priority</span><select value={draft.priority} onChange={event => setDraft(value => ({ ...value, priority: event.target.value as TaskRecord['priority'] }))}><option>Low</option><option>Normal</option><option>High</option><option>Urgent</option></select></label>
      <label className="wide-field"><span>Title</span><input required minLength={2} maxLength={200} value={draft.title} onChange={event => setDraft(value => ({ ...value, title: event.target.value }))} /></label><label><span>Assignee</span><select value={draft.assigneeEmployeeId} onChange={event => setDraft(value => ({ ...value, assigneeEmployeeId: event.target.value }))}><option value="">Unassigned</option>{members.map(item => <option key={item.id} value={item.id}>{item.fullName} ({item.employeeCode})</option>)}</select><small>Only active project members are available.</small></label><label><span>Due date</span><input type="date" value={draft.dueDate} onChange={event => setDraft(value => ({ ...value, dueDate: event.target.value }))} /></label>
      <label className="wide-field"><span>Description</span><textarea maxLength={4000} value={draft.description} onChange={event => setDraft(value => ({ ...value, description: event.target.value }))} /></label><div className="wide-field form-actions"><button className="primary-button" disabled={busy}>{busy ? 'Saving…' : 'Save task'}</button></div>
    </form></article>}
    <article className="panel table-panel"><div className="panel-heading"><div><h2>Task register</h2><p>{items.length} loaded</p></div><button className="ghost-button" onClick={() => setVersion(value => value + 1)}>Refresh</button></div>{loading ? <div className="loading-block">Loading…</div> : <div className="table-wrap"><table><thead><tr><th>Task</th><th>Project</th><th>Priority</th><th>Assignee</th><th>Due</th><th>Status</th>{mayManage && <th>Actions</th>}</tr></thead><tbody>{items.map(item => <tr key={item.id}><td><strong>{item.title}</strong><small>{item.commentCount} comments</small></td><td>{item.projectName}<small>{item.projectCode}</small></td><td><Status value={item.priority} /></td><td>{item.assigneeName || 'Unassigned'}</td><td>{item.dueDate || '—'}</td><td><Status value={item.status} /></td>{mayManage && <td className="action-cell"><button className="text-button" onClick={() => editTask(item)}>Edit</button><select className="compact-select" value="" disabled={busy} onChange={event => { if (event.target.value) void changeStatus(item, event.target.value as TaskRecord['status']); }}><option value="">Move to…</option>{taskTransitions[item.status].map(status => <option key={status} value={status}>{status}</option>)}</select></td>}</tr>)}</tbody></table></div>}</article>
  </>;
}
