// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TaskMonitoring.Api.Migrations;

public partial class InitialIdentityFoundation
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.12")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("TaskMonitoring.Api.Domain.AuditLog", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Action").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
            b.Property<Guid?>("ActorUserId").HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("IpAddress").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("MetadataJson").HasColumnType("text");
            b.Property<string>("TargetId").HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("TargetType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.Property<string>("UserAgent").HasMaxLength(512).HasColumnType("character varying(512)");
            b.HasKey("Id");
            b.HasIndex("CreatedAtUtc");
            b.HasIndex("ActorUserId", "CreatedAtUtc");
            b.ToTable("audit_logs", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.Permission", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<string>("Code").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
            b.HasKey("Id");
            b.HasIndex("Code").IsUnique();
            b.ToTable("permissions", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.RefreshToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("CreatedByIp").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<DateTime>("ExpiresAtUtc").HasColumnType("timestamp with time zone");
            b.Property<Guid?>("ReplacedByTokenId").HasColumnType("uuid");
            b.Property<string>("RevokeReason").HasMaxLength(200).HasColumnType("character varying(200)");
            b.Property<DateTime?>("RevokedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("RevokedByIp").HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<string>("TokenHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.HasKey("Id");
            b.HasIndex("TokenHash").IsUnique();
            b.HasIndex("UserId", "ExpiresAtUtc");
            b.ToTable("refresh_tokens", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.Role", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<string>("Name").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
            b.HasKey("Id");
            b.HasIndex("Name").IsUnique();
            b.ToTable("roles", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.RolePermission", b =>
        {
            b.Property<Guid>("RoleId").HasColumnType("uuid");
            b.Property<Guid>("PermissionId").HasColumnType("uuid");
            b.HasKey("RoleId", "PermissionId");
            b.HasIndex("PermissionId");
            b.ToTable("role_permissions", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.User", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("Email").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<int>("FailedLoginAttempts").HasColumnType("integer");
            b.Property<bool>("IsActive").HasColumnType("boolean");
            b.Property<DateTime?>("LockoutEndUtc").HasColumnType("timestamp with time zone");
            b.Property<string>("NormalizedEmail").IsRequired().HasMaxLength(320).HasColumnType("character varying(320)");
            b.Property<string>("PasswordHash").IsRequired().HasMaxLength(1024).HasColumnType("character varying(1024)");
            b.Property<DateTime>("UpdatedAtUtc").HasColumnType("timestamp with time zone");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").IsUnique();
            b.ToTable("users", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.UserRole", b =>
        {
            b.Property<Guid>("UserId").HasColumnType("uuid");
            b.Property<Guid>("RoleId").HasColumnType("uuid");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("user_roles", (string)null);
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.RefreshToken", b =>
        {
            b.HasOne("TaskMonitoring.Api.Domain.User", "User").WithMany("RefreshTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("User");
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.RolePermission", b =>
        {
            b.HasOne("TaskMonitoring.Api.Domain.Permission", "Permission").WithMany("RolePermissions").HasForeignKey("PermissionId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("TaskMonitoring.Api.Domain.Role", "Role").WithMany("RolePermissions").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Permission");
            b.Navigation("Role");
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.UserRole", b =>
        {
            b.HasOne("TaskMonitoring.Api.Domain.Role", "Role").WithMany("UserRoles").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.HasOne("TaskMonitoring.Api.Domain.User", "User").WithMany("UserRoles").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("Role");
            b.Navigation("User");
        });

        modelBuilder.Entity("TaskMonitoring.Api.Domain.Permission", b => b.Navigation("RolePermissions"));
        modelBuilder.Entity("TaskMonitoring.Api.Domain.Role", b =>
        {
            b.Navigation("RolePermissions");
            b.Navigation("UserRoles");
        });
        modelBuilder.Entity("TaskMonitoring.Api.Domain.User", b =>
        {
            b.Navigation("RefreshTokens");
            b.Navigation("UserRoles");
        });
#pragma warning restore 612, 618
    }
}
